import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Login • Psicologia Católica Tomista",
  description: "Bem-vindo ao site oficial da Psicologia Católica Tomista, onde você encontra informações e recursos sobre a integração da psicologia com os princípios da filosofia tomista.",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> bdcc5062df5ebc75650c61000c439acc4962154d
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
